### ISSUE TITLE
Alx fails to build with kernel 3.10-rc3

### ISSUE THREAD

**Issue by TheSiege** [mcgrof/alx#6]
I was trying to build the alx driver for the newest linux rc (been trying since rc1) following error

```
drivers/net/ethernet/atheros/alx/alx_main.c: In function 'alx_dispatch_skb':
drivers/net/ethernet/atheros/alx/alx_main.c:694:4: error: too few arguments to function '__vlan_hwaccel_put_tag'
In file included from drivers/net/ethernet/atheros/alx/alx_main.c:22:0:
include/linux/if_vlan.h:237:31: note: declared here
drivers/net/ethernet/atheros/alx/alx_main.c: In function 'alx_set_vlan_mode':
drivers/net/ethernet/atheros/alx/alx_main.c:1132:17: error: 'NETIF_F_HW_VLAN_RX' undeclared (first use in this function)
drivers/net/ethernet/atheros/alx/alx_main.c:1132:17: note: each undeclared identifier is reported only once for each function it appears in
drivers/net/ethernet/atheros/alx/alx_main.c: In function 'alx_fix_features':
drivers/net/ethernet/atheros/alx/alx_main.c:1148:17: error: 'NETIF_F_HW_VLAN_RX' undeclared (first use in this function)
drivers/net/ethernet/atheros/alx/alx_main.c:1149:15: error: 'NETIF_F_HW_VLAN_TX' undeclared (first use in this function)
drivers/net/ethernet/atheros/alx/alx_main.c: In function 'alx_set_features':
drivers/net/ethernet/atheros/alx/alx_main.c:1166:18: error: 'NETIF_F_HW_VLAN_RX' undeclared (first use in this function)
drivers/net/ethernet/atheros/alx/alx_main.c: In function 'alx_probe':
drivers/net/ethernet/atheros/alx/alx_main.c:2613:10: error: 'NETIF_F_HW_VLAN_RX' undeclared (first use in this function)
drivers/net/ethernet/atheros/alx/alx_main.c:2616:43: error: 'NETIF_F_HW_VLAN_TX' undeclared (first use in this function)
make[5]: *** [drivers/net/ethernet/atheros/alx/alx_main.o] Error 1
make[4]: *** [drivers/net/ethernet/atheros/alx] Error 2
make[3]: *** [drivers/net/ethernet/atheros] Error 2
make[2]: *** [drivers/net/ethernet] Error 2
make[1]: *** [drivers/net] Error 2
make: *** [drivers] Error 2
```

please help
I was using another way than the one in the Readme after trying that one I get:

```
Origin remote URL: git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git
This is a linux-next.git compat-drivers release

Base tree: linux-next.git
Base tree version: next-20130604
compat.git: compat-2013-03-28-4
compat-drivers release: compat-drivers-2013-03-28-5
Code metrics archive: http://bit.ly/H6BTF7
Copying compat/ ...
Copying include/ ...
Copying udev/ ...
Copying scripts/check_config.sh ...
Copying scripts/check_depmod ...
Copying scripts/compress_modules ...
Copying scripts/gen-compat-autoconf.sh ...
Copying scripts/modlib.sh ...
Copying scripts/update-initramfs ...
Copying scripts/skip-colors ...
Copying .compat_base ...
Copying .compat_base_tree ...
Copying .compat_base_tree_version ...
Copying .compat_version ...
Copying config.mk ...
Copying patches/unified-drivers/network/0001-backport-alx.patch ...

Synched with compat-drivers-2013-03-28-5
patching file alx_main.c
make -C target/linux/
make[1]: Entering directory `/home/anagromataf/drivers/alx/target/linux'
make -C /lib/modules/3.10.0-rc3/build M=/home/anagromataf/drivers/alx/target/linux modules
make[2]: Entering directory `/opt/src/linux-3.10-rc3'
/home/anagromataf/drivers/alx/target/linux/config.mk:254: "WARNING: CONFIG_CFG80211_WEXT will be deactivated or not working because kernel was compiled with CONFIG_WIRELESS_EXT=n. Tools using wext interface like iwconfig will not work. To activate it build your kernel e.g. with CONFIG_LIBIPW=m."
  CC [M]  /home/anagromataf/drivers/alx/target/linux/compat/main.o
In file included from /home/anagromataf/drivers/alx/target/linux/include/linux/compat-2.6.h:75:0,
                 from <command-line>:0:
/home/anagromataf/drivers/alx/target/linux/include/linux/compat-3.10.h:91:52: warning: 'struct fb_info' declared inside parameter list [enabled by default]
/home/anagromataf/drivers/alx/target/linux/include/linux/compat-3.10.h:91:52: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
/home/anagromataf/drivers/alx/target/linux/include/linux/compat-3.10.h: In function 'backport_fb_enable_skip_vt_switch':
/home/anagromataf/drivers/alx/target/linux/include/linux/compat-3.10.h:93:6: error: dereferencing pointer to incomplete type
make[4]: *** [/home/anagromataf/drivers/alx/target/linux/compat/main.o] Error 1
make[3]: *** [/home/anagromataf/drivers/alx/target/linux/compat] Error 2
make[2]: *** [_module_/home/anagromataf/drivers/alx/target/linux] Error 2
make[2]: Leaving directory `/opt/src/linux-3.10-rc3'
make[1]: *** [linux] Error 2
make[1]: Leaving directory `/home/anagromataf/drivers/alx/target/linux'
make: *** [linux] Error 2
```

**Comment by hadrons123** [comment]
http://lists.infradead.org/pipermail/unified-drivers/2013-July/000080.html
Comments by Luis:
Its now merged upstream as part of the Linux kernel but that driver
was modified a bit to get cleaned up given the Linux alx upstreaming
effort was dropped. The driver was cleaned up by Johannes Berg and
relicensed to GPLv2 or later. I just kicked out a backports release
that lets you use the new upstreamed driver:

https://www.kernel.org/pub/linux/kernel/projects/backports/2013/06/18/backports-20130618.tar.bz2
